### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(ModelViewer)
add_subdirectory(ModelViewerContent)
add_subdirectory(App)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    ModelViewerplugin
    ModelViewerContentplugin)